{{- $pi := (index .Values "pipelineImporter") | default dict -}}
{{- $git := (index $pi "gitCredentials") | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nifi.fullname" . }}-git-credentials
type: Opaque
stringData:
  username: {{ (index $git "username") | default "" | quote }}
  password: {{ (index $git "password") | default "" | quote }}
