{{- $ir := (.Values.nifi.ingressRoute | default dict) -}}
{{- if (index $ir "enabled") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "nifi.fullname" . }}-headers
  namespace: {{ include "nifi.namespace" . }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "{{ (index $ir "host") | default "" }}"
      X-Forwarded-Port: "443"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
{{- end }}
