{{- if and .Values.nifi.auth.singleUser.enabled .Values.nifi.auth.singleUser.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nifi.auth.singleUser.secretName | default (printf "%s-single-user" (include "nifi.fullname" .)) }}
  namespace: {{ include "nifi.namespace" . }}
  labels:
    {{ include "nifi.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin: {{ .Values.nifi.auth.singleUser.password | quote }}
{{- end }}

