{{- if .Values.kafka.ssl.enabled }}
{{- $env := .Values.environment | default "dev" }}
{{- $certPath := printf "cert/%s" $env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kafka.ssl.secretName }}
  namespace: {{ .Values.metadata.namespace }}
type: Opaque
data:
  # Los certificados se cargan desde cert/{{ $env }}/
  keystore.jks: {{ .Files.Get (printf "%s/keystore.jks" $certPath) | b64enc }}
  truststore.jks: {{ .Files.Get (printf "%s/truststore.jks" $certPath) | b64enc }}
stringData:
  keystore.password: {{ .Values.kafka.ssl.keystorePassword | quote }}
  truststore.password: {{ .Values.kafka.ssl.truststorePassword | quote }}
  key.password: {{ .Values.kafka.ssl.keyPassword | quote }}
{{- end }}
